### ISSUE TITLE
EmbeddedCheckout is not using the svelte-stripe package in the example

### ISSUE THREAD

**Issue by gagansuie** [joshnuss/svelte-stripe#106]
### Describe the bug

https://github.com/joshnuss/svelte-stripe/blob/2375ab8234b72d0ee96685ebce7252f0338c2c77/src/routes/examples/embedded-checkout/%2Bpage.svelte#L5

This is using the EmbeddedCheckout from $lib and not the svelte-stripe package itself.

### Reproduction

go to the link and see the import

https://github.com/joshnuss/svelte-stripe/blob/2375ab8234b72d0ee96685ebce7252f0338c2c77/src/routes/examples/embedded-checkout/%2Bpage.svelte#L5

### Severity

annoyance

**Comment by joshnuss** [comment]
Hi @gagansuie!

That ok, it's just how svelte-package works.

The components are in the `$lib` folder and the `src/routes` are used for docs.

It wouldn't be possible to import from the npm package, because installing the npm package in the repo would create a circular reference.

So I think it's working as intended.
