### ISSUE TITLE
id attribute on card elements

### ISSUE THREAD

**Issue by simplegram-io** [joshnuss/svelte-stripe#47]
It would be great if one could add an _id_ to the CardNumber, CardExpiry and CardCvc elements so labels work with them.

Is that possible or do stripe elements prevent that?

**Comment by joshnuss** [comment]
Hi @simplegram-io,

I don't believe you can set the `id` on those inputs, likely because they are inside an iframe. So targeting them from a label in different frame probably wouldn't work.

Good news is that labels are supported by Stripe Elements. You should be able to set the `labels` prop on the `<Elements/>` component.

Feel free to re-open if that doesn't work or if you have any more questions.
