### ISSUE TITLE
client secret is not updated when creating new intent on the fly (on change)

### ISSUE THREAD

**Issue by MelodicCrypter** [joshnuss/svelte-stripe#48]
Details:
- Has 2 products, monthly and yearly subscriptions

Flow:
1. On load, i would create a default subscription intent (monthly) then pass the clientSecret to the `<Elements {stripe} clientSecret={userClientSecret} />`
2. I test pay it, and it is successful
3. But, when I change the payment terms like to yearly, coz users has the right to change it either to monthly or yearly in the payment page, so if user decides to pay as yearly instead, I would delete previous subscription intent, then create new subscription intent, then the returned client secret I will update the variable "userClientSecret" which already mounted on load.
4. I click Pay button, but it wouldn't pass, it will show 400 error

Why is that? Is the client secret not automatically updated? I mean, do I have to remount the component?

**Comment by gentlemanjohn** [comment]
I'm having a similar issue trying to change the client secret before the payment is confirmed. 

In my case I actually initialize the form with a client secret from a setup intent before trying to switch to a client secret from a payment intent. I'm trying this because I have a donation type payment form that allows for a custom amount; however, I cannot initialize the Elements component without a client secret. I cannot create a payment intent without attaching an amount up front, so I'm stuck with $.50 (the minimum) incomplete transactions if the user visits the form but doesn't complete the process (where I update the payment intent amount to whatever the user enters). I was hoping that using the secret from a setup intent would be a workaround...

**Comment by joshnuss** [comment]
Hi,

The `clientSecret` (from the Payment Intent) is required to mount the component when using a `<PaymentElement>` or `<LinkAuthenticationElement/>`. It is not  required if you are using other components like `<CreditCard/>`.

According to Stripe's docs, [`elements.create()` takes a `clientSecret`](https://stripe.com/docs/js/elements_object/create) and [`element.update() does not support updating the client secret`](https://stripe.com/docs/js/elements_object/update)

There are 2 workarounds I can think of:

1. Remounting using Svelte's `{#key ...}` syntax. But keep in mind, remounting will wipe anything the user has already inputted.
2. Replacing `<PaymentElement/>` with `<CreditCard/>` in this case.

Also, it might be good idea to discuss this issue on Stripe's Slack, to gain more context about why this use case isn't support right now.

**Comment by laszlo1337** [comment]
I have big problem with this. I am using the library like this:

```
{#if stripe && clientSecret}
	<Elements bind:elements {stripe} {clientSecret} theme="night" labels="floating" {variables} {rules}>
		<PaymentElement
			on:change={({ detail }) => (paymentDataFilled = detail.complete)}
			on:ready={() => (elementsFullyRendered = true)}
			options={{
				layout: { type: 'accordion' },
				fields: { billingDetails: 'never' },
				business: { name: 'QR Badger' },
			}}
		/>
	</Elements>
{/if}
```

But when I need to recreate the payment intent due to discount being applied, I was given error that stripe instances do not match. 

So I tried wrapping this into #key:

```
// script tag
$: elementsKey = stripe && clientSecret ? `${stripe}-${clientSecret}` : null

// page component body
{#key elementsKey}
	<Elements bind:elements {stripe} {clientSecret} theme="night" labels="floating" {variables} {rules}>
		<PaymentElement
			on:change={({ detail }) => (paymentDataFilled = detail.complete)}
			on:ready={() => (elementsFullyRendered = true)}
			options={{
				layout: { type: 'accordion' },
				fields: { billingDetails: 'never' },
				business: { name: 'QR Badger' },
			}}
		/>
	</Elements>
{/key}
```

but now after `invalidate()` is called when discount is being applied, I get:
```
PaymentElement.svelte:16 Uncaught (in promise) TypeError: Cannot destructure property 'elements' of 'getContext(...)' as it is undefined.
    at instance8 (PaymentElement.svelte:16:11)
    at init (Component.js:135:5)
    at new PaymentElement (PaymentElement.svelte:44:24)
    at Array.create_default_slot_1 (+page.svelte?t=1712141238496:841:19)
    at create_slot (utils.js:165:22)
    at create_if_block2 (EmbeddedCheckout.svelte:24:38)
    at create_fragment14 (Elements.svelte:64:24)
    at init (Component.js:148:34)
    at new Elements (Elements.svelte:60:41)
    at create_key_block (+page.svelte?t=1712141238496:917:15)
```

Which apparently should work as suggested by @joshnuss 

Please help 🙏🏻

**Comment by laszlo1337** [comment]
I have big problem with this. I am using the library like this:

```
{#if stripe && clientSecret}
	<Elements bind:elements {stripe} {clientSecret} theme="night" labels="floating" {variables} {rules}>
		<PaymentElement
			on:change={({ detail }) => (paymentDataFilled = detail.complete)}
			on:ready={() => (elementsFullyRendered = true)}
			options={{
				layout: { type: 'accordion' },
				fields: { billingDetails: 'never' },
				business: { name: 'app' },
			}}
		/>
	</Elements>
{/if}
```

But when I need to recreate the payment intent due to discount being applied, I was given error that stripe instances do not match. 

So I tried wrapping this into #key:

```
// script tag
$: elementsKey = stripe && clientSecret ? `${stripe}-${clientSecret}` : null

// page component body
{#key elementsKey}
	<Elements bind:elements {stripe} {clientSecret} theme="night" labels="floating" {variables} {rules}>
		<PaymentElement
			on:change={({ detail }) => (paymentDataFilled = detail.complete)}
			on:ready={() => (elementsFullyRendered = true)}
			options={{
				layout: { type: 'accordion' },
				fields: { billingDetails: 'never' },
				business: { name: 'app' },
			}}
		/>
	</Elements>
{/key}
```

but now after `invalidate()` is called when discount is being applied, I get:
```
PaymentElement.svelte:16 Uncaught (in promise) TypeError: Cannot destructure property 'elements' of 'getContext(...)' as it is undefined.
    at instance8 (PaymentElement.svelte:16:11)
    at init (Component.js:135:5)
    at new PaymentElement (PaymentElement.svelte:44:24)
    at Array.create_default_slot_1 (+page.svelte?t=1712141238496:841:19)
    at create_slot (utils.js:165:22)
    at create_if_block2 (EmbeddedCheckout.svelte:24:38)
    at create_fragment14 (Elements.svelte:64:24)
    at init (Component.js:148:34)
    at new Elements (Elements.svelte:60:41)
    at create_key_block (+page.svelte?t=1712141238496:917:15)
```

Which apparently should work as suggested by @joshnuss 

Please help 🙏🏻
