### ISSUE TITLE
Styling: Classes can't reach the font of the input.

### ISSUE THREAD

**Issue by iandoesallthethings** [joshnuss/svelte-stripe#49]
I'm using tailwind and we have a bunch of custom utility classes set up for our design system. I'm trying to send those classes into the stripe elements, but it looks as though I can only reach the text inside the input using the style prop. Classes (even non-tailwind ones specified with global don't affect the text at all.

```ts
<script lang="ts">
const classes: StripeElementClasses = {
  base: 'stripe-input'
}
</script>

<CardNumber bind:value={cardElement} {classes} />

<style>
:global(.strip-input) {
  font-color: blue;
  font-size: x-large;
}
</style>
```

**Comment by joshnuss** [comment]
Hi @iandoesallthethings,

Classes should work, see example here:
https://github.com/joshnuss/svelte-stripe/blob/main/src/routes/examples/credit-card/index.svelte#L72

Is it because you have a spelling error? `.strip-input` is missing an `e`

As for Tailwind, I don't think they would work because, see answer here:
https://stackoverflow.com/a/64420507

I think it's because the inputs are inside an iframe, and the iframe doesn't import tailwind's `.css` file.

I beleive this answers the question, so I'm closing. Feel free to re-open if it still doesn't work!
